[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libsqlite3-dev libpq5 python3-dev build-essential",
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
]

[start]
cmd = "python manage.py migrate && gunicorn project.wsgi:application --bind 0.0.0.0:$PORT"